### PR TITLE
Stop Entry support via the experimental client that didn't use Newtonsoft JSON. Uses Global  API.

### PR DESCRIPTION
**Pull request by leonmeijer**
New API: EndTimeEntryAsync

### CODE REVIEW

**Comment by Morasiu** [comment]
Hey! 

Thanks for your contribution! 

Could you add a simple test to check your newly added endpoint?

**Comment by Morasiu** [comment]
Also, I've found [this](https://clockify.me/developers-api#operation--v1-workspaces--workspaceId--user--userId--time-entries-patch) and I can do a similar thing. But I'm not sure if this is specific a premium feature or not.

**Comment by leonmeijer** [comment]
The changes work with the URL you had for the experimental URL (https://api.clockify.me/api/). It does not work with the regular client (https://api.clockify.me/api/v1).
And I can confirm it works with the free accounts.

**Comment by Morasiu** [comment]
Oh... I can see you've just set up an Azure Pipeline. It can be useful. Thanks!

**Comment by leonmeijer** [comment]
I am also doing some experiments

**Comment by Morasiu** [comment]
Great. Call me (using @Morasiu) when you will be done with this PR

**Comment by Morasiu** [comment]
@leonmeijer Um... Should I close PR?

**Pull request closed without merging**
