### PR TITLE
<I><#23><Find Project By Id><Added and tested FindProjectWithId>

### PR DESCRIPTION
**Pull request by stefan99x**
Added the Method: `FindProjectWithId`
Tested the Method: `FindProjectWithId`

Description: This method will return a project with it's coresponding id. 

Arguments: 

- string workspaceId (the workspace Id)
- string id (the project id)

### CODE REVIEW

**Comment by stefan99x** [comment]
Apparently, the tests on the `continuous-integration/travis-ci/pr failed` because it could no connect to the Clockify account. I could provide the Clockify dummy account API key if it helps.

image

**Comment by Morasiu** [comment]
Yeah, Travis has some issues. I'll check that

**Comment by Morasiu** [comment]
Looks good, by it should be merge to `develop` next time ;)

**Comment by stefan99x** [comment]
> Looks good, by it should be merge to `develop` next time ;)

my bad =))

**Pull request merged**
