### PR TITLE
<I><#23><Find all time entries by project><Added and tested FindAllTimeEntriesForProjectAsync>

### PR DESCRIPTION
**Pull request by stefan99x**
Added the Method: FindAllTimeEntriesForProjectAsync
Tested the Method: FindAllTimeEntriesForProjectAsync

Description: This method will return all time-entries in a project, with ability to be filtered.

Arguments:
string workspaceId (the workspace Id)
string id (the project id)

Arguments for filtering data:
            string description = null,
            DateTimeOffset? start = null,
            DateTimeOffset? end = null,
            string task = null,
            bool? projectRequired = null,
            bool? taskRequired = null,
            bool? considerDurationFormat = null,
            bool? hydrated = null,
            bool? inProgress = null,
            int page = 1,
            int pageSize = 50

PS: There are a lot of changes the code formated on run.

### CODE REVIEW

**Comment by Morasiu** [comment]
Base your PR on `develop` branch please

**Comment by Morasiu** [comment]
And now there is a conflict... Damn.

**Comment by stefan99x** [comment]
I think the merge conflict is produced by the formatted code.

**Comment by Morasiu** [comment]
I'll try to fix that.

**Pull request merged**
